spring.application.name=Spring_test
spring.datasource.url=jdbc:sqlite:ledger.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
server.port = 8081
